import request from './request'

export const pageAdminAfterSales = params => request.get('/admin/after-sales', { params })
export const getAdminAfterSale = id => request.get(`/admin/after-sales/${id}`)
export const approveAfterSale = (id, data) => request.post(`/admin/after-sales/${id}/approve`, data)
export const rejectAfterSale = (id, data) => request.post(`/admin/after-sales/${id}/reject`, data)
export const completeAfterSale = (id, data) => request.post(`/admin/after-sales/${id}/complete`, data)
export const requestAfterSaleEvidence = (id, data) => request.post(`/admin/after-sales/${id}/request-evidence`, data)
export const createAfterSaleTicket = (id, data) => request.post(`/admin/after-sales/${id}/tickets`, data)
export const createEvidenceAudit = (id, data = {}) => request.post(`/after-sale-evidences/${id}/audits`, data)
export const listAfterSaleEvidenceAudits = id => request.get(`/admin/after-sales/${id}/evidence-audits`)
export const assessAfterSaleRisk = (id, data = {}) => request.post(`/admin/after-sales/${id}/risk-assessment`, data)
export const getAfterSaleRiskAssessment = id => request.get(`/admin/after-sales/${id}/risk-assessment`)
export const pageAfterSaleRiskAssessments = params => request.get('/admin/risk-assessments', { params })
export const listReplyDrafts = id => request.get(`/admin/after-sales/${id}/reply-drafts`)
export const generateReplyDraft = (id, data) => request.post(`/admin/after-sales/${id}/reply-drafts`, data)
export const useReplyDraft = (id, draftId, data) => request.post(`/admin/after-sales/${id}/reply-drafts/${draftId}/use`, data)
export const discardReplyDraft = (id, draftId, data) => request.post(`/admin/after-sales/${id}/reply-drafts/${draftId}/discard`, data)
